name: Kicad CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: download and install kicad
        run: |
          PCBPATH="ESPnow_Receiver.kicad_pcb"
          sudo apt update && sudo apt upgrade
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:kicad/kicad-6.0-releases -y
          sudo apt update
          sudo apt install kicad -y
          sudo apt-get install -y xvfb git
          git clone https://github.com/openscopeproject/InteractiveHtmlBom.git
          
